### ISSUE TITLE
Drawer doesn't show when navigating back from another stack or tab

### ISSUE THREAD

**Issue by juddey** [aspect-apps/react-native-navigation-drawer-extension#10]
Hello, me again.

I've been playing around with `2.0.1` and I'm seeing the same behaviour as the movie I posted in #8, when I come back from another stack or tab in the navigator.

The app itself does not crash this time however - all that happens is the overlay fails to show. And the thing is, the failures are inconsistent, sometimes the overlay shows as expected!

Have you any suggestions as to where I can start debugging this? I don't want to post something with not enough information and waste everyones time.

**Comment by juddey** [comment]
Been working with this today, trying to get a solution.... The first thing I thought I would do is add the code directly to my project so I could debug. I'm using javascript not typescript so converted the package so I could use it more easily

Added it with just plain js, and ever since, its been working without flaw.

**Comment by lukebrandonfarrell** [comment]
Closing this as does not seem like an issue in version 3.

**Comment by juddey** [comment]
oops! thought I closed this - its not an issue.
