### ISSUE TITLE
dismissDrawerWithAnimation is not work properly after upgrade to latest wix navigation

### ISSUE THREAD

**Issue by lisichka999** [aspect-apps/react-native-navigation-drawer-extension#16]
dismissDrawerWithAnimation function does work after I update to wix navigation to 4.
When I call this function I received the following error:

> YellowBox.js:71 Possible Unhandled Promise Rejection (id: 0):
> Error: Could not dismiss Overlay. Overlay with id Component34 was not found.
> Error: Could not dismiss Overlay. Overlay with id Component34 was not found.
>     at Object.fn [as dismissOverlay] (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:3862:36)
>     at NativeCommandsSender.dismissOverlay (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:3017:42)
>     at Commands.dismissOverlay (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:97738:48)
>     at NavigationRoot.dismissOverlay (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2863:30)
>     at http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:364577:47
>     at http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:55452:23
>     at TimingAnimation.__debouncedOnEnd (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:58560:18)
>     at TimingAnimation.stop (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:59040:14)
>     at AnimatedValue.stopAnimation (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:55409:44)
>     at AnimatedValue.__detach (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:55352:14)

it come from here:
```


  dismissDrawerWithAnimation() {
       const { direction } = this.props;
       const closeValues = {
         left: -this.drawerWidth,
         right: this.screenWidth,
         top: -this.drawerHeight,
         bottom: this.screenHeight
       };
 
       // Animate side menu close
       Animated.timing(this.state.sideMenuOpenValue, {
         toValue: closeValues[direction],
         duration: this.props.animationCloseTime
       }).start(() => {
         Navigation.dismissOverlay(this.props.componentId);//This is a problematic line
       });
 
       // Animate outside side menu opacity
       Animated.timing(this.state.sideMenuOverlayOpacity, {
         toValue: 0,
         duration: this.props.animationCloseTime
       }).start();
     }
   }

```

**Comment by lukebrandonfarrell** [comment]
Thanks for the issues @lisichka999 

We are still yet to upgrade to the latest version on Wix in our production apps. Which I estimate won't be until Q2. I'll keep an eye on this, but can't tackle it directly at this moment. The only thing I see is that Wix may have changed their `dismissOverlay` logic, if you could dig into this issue and provide more info about the Wix v4 changes, then we may be able to make PR.

**Comment by lukebrandonfarrell** [comment]
@lisichka999 Going to close this. As we have done the RNN upgrade internally and everything seems to work. Let me know if that is not the case for you?
