### ISSUE TITLE
Closing drawer with swipe gesture

### ISSUE THREAD

**Issue by sabin10** [aspect-apps/react-native-navigation-drawer-extension#22]
Hey. Nice extension.

Is there any way to close the drawer with a swiping gesture, similar to the opening gesture? I attached an image to make it more clear.
If there is no implementation for this, could you give some directions? Maybe I can help with a PR

<img width="354" alt="Screenshot 2020-04-14 at 18 05 35" src="https://user-images.githubusercontent.com/35928720/79240529-93dc0000-7e7a-11ea-81cb-f7723e66fa14.png">

**Comment by Ghya** [comment]
Yes indeed, it would be really nice, let me know if you manage to do it ;)

**Comment by lukebrandonfarrell** [comment]
@sabin10 You'd have to use a GestureHandler on the higher order drawer component. Then just map that to the animation, no need to fire events, this is slightly easier than opening with a swipe gesture which requires an event system. You a free to have a shot at this

**Comment by rodriigovieira** [comment]
This is fixed on #36.

![Imagem-do-iOS](https://user-images.githubusercontent.com/7014073/98970828-29ae3b00-24ef-11eb-8374-0009f73009aa.gif)

**Comment by csokdara-thefoundry-app** [comment]
Is there anyway to disable or customise the sensitivity of the swipe to close feature? I got a scroll list inside the drawer and when I scroll up and down the swipe to close trigger what scroll up gesture.

**Comment by rodriigovieira** [comment]
@csokdara-thefoundry-app not at the moment, but I'll try to make a PR to implement this in the next week or so. I'll let you know.
