### ISSUE TITLE
Right Drawer not working as intended

### ISSUE THREAD

**Issue by byonghun** [aspect-apps/react-native-navigation-drawer-extension#24]
Thanks for this library as react-native-navigation drawers is a pain to work with.

The issue I have is that the right drawer is not working for me. The left drawer works great but I am having issues with the right drawer. I can display the content in the right drawer but `dismissDrawer` doesn't close the right drawer. If you can help me out that would be great.

<SideMenuView
                right={() => {
                    RNNDrawer.showDrawer({
                        component: {
                            name: "gomedal.Notifications",
                            passProps: {
                                swipeSensitivity: .7,
                                animationOpenTime: 300,
                                animationCloseTime: 300,
                                direction: "left",
                                dismissWhenTouchOutside: true,
                                drawerScreenWidth: "85%" || 445, // Use relative to screen '%' or absolute
                                drawerScreenHeight: "100%" || 700,
                                parentComponentId: 'CenterStack', // Custom prop, will be available in your custom drawer component props
                            }
                        }
                    })
                }}
                left={() => {
                    RNNDrawer.showDrawer({
                        component: {
                            name: "gomedal.ProfileDrawer",
                            passProps: {
                                animationOpenTime: 300,
                                animationCloseTime: 300,
                                direction: "left",
                                dismissWhenTouchOutside: true,
                                drawerScreenWidth: "85%" || 445, // Use relative to screen '%' or absolute
                                drawerScreenHeight: "100%" || 700,
                                parentComponentId: 'CenterStack', // Custom prop, will be available in your custom drawer component props
                            }
                        }
                    })
                }}
                style={{ flex: 1 }}
            >
             <Children/>
          </SideMenuView>

**Comment by byonghun** [comment]
> Thanks for this library as react-native-navigation drawers is a pain to work with.
> 
> The issue I have is that the right drawer is not working for me. The left drawer works great but I am having issues with the right drawer. I can display the content in the right drawer but `dismissDrawer` doesn't close the right drawer. If you can help me out that would be great.
> 
> <SideMenuView
> right={() => {
> RNNDrawer.showDrawer({
> component: {
> name: "gomedal.Notifications",
> passProps: {
> swipeSensitivity: .7,
> animationOpenTime: 300,
> animationCloseTime: 300,
> direction: "left",
> dismissWhenTouchOutside: true,
> drawerScreenWidth: "85%" || 445, // Use relative to screen '%' or absolute
> drawerScreenHeight: "100%" || 700,
> parentComponentId: 'CenterStack', // Custom prop, will be available in your custom drawer component props
> }
> }
> })
> }}
> left={() => {
> RNNDrawer.showDrawer({
> component: {
> name: "gomedal.ProfileDrawer",
> passProps: {
> animationOpenTime: 300,
> animationCloseTime: 300,
> direction: "left",
> dismissWhenTouchOutside: true,
> drawerScreenWidth: "85%" || 445, // Use relative to screen '%' or absolute
> drawerScreenHeight: "100%" || 700,
> parentComponentId: 'CenterStack', // Custom prop, will be available in your custom drawer component props
> }
> }
> })
> }}
> style={{ flex: 1 }}
> >

Looking into this further, it seems as if `componentDidAppear` and `componentDidDisappear` is never called when right swiping or calling showDrawer with `right` direction.

**Comment by byonghun** [comment]
Nvm, found out why this was occurring.

**Comment by lukebrandonfarrell** [comment]
@byonghun What was the solution to the issue? Would you mind posting it here so other can find it in the future?
