### ISSUE TITLE
Doesn't work well with other HOC implementations

### ISSUE THREAD

**Issue by eurobob** [aspect-apps/react-native-navigation-drawer-extension#26]
I'm using a function to wrap my components in an emotion theme provider, and an apollo provider.

This extension only works when I don't include that function. Otherwise, it works in as much as the drawer appears. But there is no animation, and no overlay opacity, and no way to dismiss the drawer.

I have tried with only the theme provider and only the apollo provider to see if it was specific, but it appears to be affected no matter what

```
Navigation.registerComponent(
  'SortIntentions',
  () => UIProvider(SortIntentions),
  () => RNNDrawer.create(SortIntentions),
);
```

```
export default function UIProvider(Component) {
  return props => (
    <ThemeProvider theme={theme}>
      <ApolloProvider client={client}>
        <ApolloHooksProvider client={client}>
          <Component {...props} />
        </ApolloHooksProvider>
      </ApolloProvider>
    </ThemeProvider>
  );
}
```

# EDIT
**I found that I have to pass the return value of RNNDrawer into my own function, but it would be nice to be able to chain as I do with my other components. Just feels cleaner**

```
Navigation.registerComponent('SortIntentions', () =>
  UIProvider(RNNDrawer.create(SortIntentions)),
);
```

**Comment by lukebrandonfarrell** [comment]
@eurobob This is the way we do it with multiple HOC. This seems just fine.
