### ISSUE TITLE
Animation not working for top direction

### ISSUE THREAD

**Issue by eurobob** [aspect-apps/react-native-navigation-drawer-extension#27]
Left and right are fine. But coming from the top only does a fade in.

Also, from the bottom doesn't show the component for me. Only the opacity overlay over the rest of the current screen

**Comment by eurobob** [comment]
This was an issue when trying to set the height to 50% by setting `drawerScreenHeight: 0.5` as per the docs, which need updating to not suggest a 0-1 value

**Comment by lukebrandonfarrell** [comment]
@eurobob Nice spot, if you could make a PR to the docs that would be great. Cheers
