### ISSUE TITLE
SideBar is Covering Bottom tabs 

### ISSUE THREAD

**Issue by prateekpareekvyas** [aspect-apps/react-native-navigation-drawer-extension#49]
Side Bar is covering bottom tabs . and floating button does anybody have solution for this . for reference you can check this packages example gif https://raw.githubusercontent.com/LukeBrandonFarrell/open-source-images/master/react-native-navigation-drawer-extension/left-drawer.gif  . does anyone have solution for this

**Comment by lukebrandonfarrell** [comment]
@prateekpareekvyas this is intended behaviour

**Comment by prateekpareekvyas** [comment]
is there any way to avoid this

**Comment by lukebrandonfarrell** [comment]
@prateekpareekvyas Probably not, as the drawer uses `showOverlay` under the hood
