### ISSUE TITLE
Performance issue.

### ISSUE THREAD

**Issue by CursedWizard** [aspect-apps/react-native-navigation-drawer-extension#59]
Hi. Thank you guys for this project. I used it as a reference for writing my own bottom sheet component extension for RNN.

So i wanted to ask why you decided to use react-native default solutions for animating the drawer when there are [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) libraries that are seemingly way better in terms of performance. I myself used these libraries for making the bottom sheet component, you can check out how i implemented it here - [bottom sheet](https://github.com/CursedWizard/react-native-navigation-bottom-sheet).

You also were putting `useNativeDriver: false` throughout the code and using `marginLeft` for animating the drawer which is, as far as i know, damages performance.

**Comment by lukebrandonfarrell** [comment]
@CursedWizard A improvement would be to use transforms and translateX/translateY which would allow us to use native driver. Feel free to make a PR.

**Comment by rodriigovieira** [comment]
I believe this one can was handled on #60 and can be closed @lukebrandonfarrell!

**Comment by lukebrandonfarrell** [comment]
Awesome, thanks @rodriigovieira
