### ISSUE TITLE
Hook up to react native navigation tab?

### ISSUE THREAD

**Issue by TheTalonHughes** [aspect-apps/react-native-navigation-drawer-extension#67]
This is more of a general question. Can this be triggered by a react native navigation bottom tab?

**Comment by lukebrandonfarrell** [comment]
@TheTalonHughes I don't see why not, what have you tried so far?

**Comment by TheTalonHughes** [comment]
@lukebrandonfarrell I am currently using the built in side menu by using Navigation.events().registerBottomTabSelectedListener like so

```
  Navigation.events().registerBottomTabSelectedListener(
    ({ selectedTabIndex }) => {
      if (selectedTabIndex === 3) {
        Navigation.mergeOptions(BottomTabsComponentId, {
          bottomTabs: {
            drawBehind: true,
            visible: false,
          },
          sideMenu: {
            right: {
              visible: true,
            },
          },
        });
      }
    }
  );
  ```

**Comment by lukebrandonfarrell** [comment]
@TheTalonHughes You wouldn't use the side menu view include with RNN, you instead would invoke the RN library,  going to move this to discussions as there isn't any issue here.
